language: php
php:
    - 5.5
    - 5.6

before_script:
    - composer self-update
    - composer update --prefer-source --dev

script:
    - make tests phpcs

notifications:
    irc: "irc.freenode.org#roave"
    email: false
